[project]
name = "manim-math"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "importlib-metadata>=8.7.1",
    "manim==0.19.0",
    "pycairo==1.25.1",
]
